apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-ml-deployment
  namespace: dev
spec:
  template:
    spec:
      containers:
        - name: banking-ml
          env:
            - name: ENVIRONMENT
              value: "development"
            - name: DEBUG
              value: "true"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"