# configs/model_config.yaml
# Configuration for Banking ML Pipeline

project:
  name: Banking ML Pipeline
  version: 1.0.0

paths:
  data_dir: data
  models_dir: models
  logs_dir: logs
  output_dir: outputs

preprocessing:
  scaling_method: robust
  encoding_method: onehot
  numeric_features:
    - age
    - income
    - account_age_months
    - num_products
    - avg_balance
    - max_balance
    - monthly_transactions
    - avg_transaction_amount
    - max_transaction_amount
    - digital_usage_rate
    - credit_score
    - existing_loans
    - previous_defaults
    - payment_history_score
    - loan_amount_requested
    - loan_term_months
    - total_relationship_value
    - risk_score
    - engagement_score
  categorical_features:
    - education
    - occupation
    - employment_type
    - marital_status
    - loan_purpose

segmentation:
  algorithm: kmeans
  n_clusters_range: [2, 10]
  random_state: 42
  n_init: 10
  max_iter: 300

prediction:
  models:
    - logistic_regression
    - random_forest
    - xgboost
  test_size: 0.3
  random_state: 42
  use_smote: true
  cross_validation_folds: 5

model_params:
  logistic_regression:
    max_iter: 1000
    random_state: 42
  random_forest:
    n_estimators: 100
    max_depth: 10
    random_state: 42
  xgboost:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    random_state: 42

api:
  host: 0.0.0.0
  port: 5000
  debug: false

monitoring:
  drift_threshold: 0.1
  performance_threshold: 0.85
  retraining_interval_days: 30