apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-ml
  labels:
    app: banking-ml
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: banking-ml
  template:
    metadata:
      labels:
        app: banking-ml
    spec:
      containers:
        - name: banking-ml
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: banking-ml-secrets
                  key: database_url
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}